FROM python:3.6
ENV PYTHONUNBUFFERED=1

RUN pip install --upgrade pip && pip install virtualenv
RUN virtualenv /venv && . /venv/bin/activate && pip install --upgrade pip && pip install zappa

RUN mkdir /app
WORKDIR /app
