version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6.1
        environment:
          SECRET_KEY: (jg_#jns8rl8_$^j9--wvs537mzavivm0eqx03cqg*wj4m(k@e
          DEBUG: true
          POSTGRES_HOST: localhost
          POSTGRES_NAME: grassparty
          POSTGRES_USER: grassparty
          POSTGRES_PASSWORD: grasspartypassword
      - image: circleci/postgres:9.6.2
        environment:
          POSTGRES_DB: grassparty
          POSTGRES_USER: grassparty
          POSTGRES_PASSWORD: grasspartypassword
          POSTGRES_INITDB_ARGS: --encoding=UTF-8
    steps:
      - checkout
      - restore_cache:
          key: deps1-{{ .Branch }}-{{ checksum "requirements.txt" }}
      - run:
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
      - save_cache:
          key: deps1-{{ .Branch }}-{{ checksum "requirements.txt" }}
          paths:
            - "venv"
      - run:
          command: |
            . venv/bin/activate
            coverage run ./manage.py test
      - run:
          command: |
            codecov
      - store_artifacts:
          path: test-reports/
          destination: tr1

